// Every teaching entry is a Chinese / English pair. Both languages share one lesson structure.
window.Course = {
  title:['如何做好页面布局','Designing Better Page Layouts'],
  subtitle:['一个学习数据看板，从混乱到清晰','One learning dashboard, from clutter to clarity'],
  lessons:[
    {title:['信息分区与视觉层级','Information & Visual Hierarchy'],short:['信息分区','Structure'],
    intro:['先决定用户需要看到什么，再决定元素放在哪里。本章始终改进同一个学习数据看板：帮助学生快速了解学习进度，再查看趋势和课程分布。','Decide what users need to see before placing elements. Throughout this chapter, we improve one learning dashboard: students first check progress, then explore trends and course distribution.'],
    task:['把重要指标放在趋势图之前，并用区域边界检查信息分组。比较改进前后，你能否更快找到本周学习时长？','Place key metrics before the trend chart and inspect groups using region outlines. Compare the two versions: can you find weekly study time more quickly?'],
    theory:[
      [['从用户任务确定顺序','Let the task set the order'],['本案例的首要任务是快速了解学习状况，次要任务是分析原因。因此先呈现指标摘要，再呈现趋势与课程分布。先画出内容清单并标记主次，可避免把所有模块设计得同样突出。','The primary task is to check learning progress; the secondary task is to understand why it changed. Show summary metrics before trends and course distribution. List the content and rank its importance before styling it, so every module does not compete equally.']],
      [['用区域表达内容关系','Group related content into regions'],['导航用于选择位置，工具栏用于执行操作，主区域用于阅读结果。将同一任务的内容靠近，并保留组间留白。背景和边界可以辅助分组，但不能替代合理的内容组织。','Navigation selects a location, the toolbar offers actions, and the main area presents results. Keep content serving the same task close together and separate groups with space. Backgrounds and borders support grouping but cannot replace clear organization.']],
      [['建立可辨认的层级','Build a recognizable hierarchy'],['本周时长等关键数字需要突出；模块标题次之；时间范围和单位作为辅助信息。通过字号、字重、位置与留白建立差异。不要仅靠颜色传达主次，也不要把所有标题放大。','Emphasize key values such as weekly study time, followed by module titles, then supporting units and time ranges. Use size, weight, position and spacing together. Do not rely only on color or enlarge every heading.']],
      [['文档顺序也是阅读顺序','Document order is reading order'],['语义结构应在没有装饰时仍能阅读。CSS 改变位置不一定改变键盘或屏幕阅读器的顺序。本案例让摘要在图表之前出现在文档中；示例的“改进前”只是教学反例，不应作为最终布局。','Semantic structure should remain readable without decoration. CSS positioning does not necessarily change keyboard or screen-reader order. This case places summaries before charts in the document. The “Before” view is a teaching counterexample, not a final layout.']]],
    takeaway:['先用信息分区与顺序解决“看什么”，再用视觉层级解决“先看什么”。','Use grouping and order to decide what is shown, then hierarchy to guide what is seen first.']},
    {title:['留白与间距系统','Whitespace & Spacing'],short:['间距系统','Spacing'],
    intro:['沿用上一节的信息结构，调整学习指标卡的内部空间。留白要表达内容关系，同时保证卡片在有限宽度内可读。','Keep the previous information structure and adjust the metric card’s internal space. Whitespace should communicate relationships while keeping the card readable within a limited width.'],
    task:['固定声明宽度，增大内边距，再切换两种盒模型。观察内容宽度和边框盒宽度哪个发生变化，并解释原因。','Keep the declared width fixed, increase padding, then switch box models. Observe whether content width or border-box width changes and explain why.'],
    theory:[
      [['组内紧，组间松','Closer within groups, wider between groups'],['“本周学习”和“18.5 小时”属于一组，应该比它们与下一张卡片的距离更近。这体现亲近性：距离帮助人判断哪些内容属于一起。留白不是剩下来的空间，而是组织信息的工具。','“Weekly study” and “18.5 hours” form one group and should be closer to each other than to the next card. This illustrates proximity: distance helps people recognize relationships. Whitespace is a tool for organizing information, not leftover space.']],
      [['建立尺度，而不是死记数字','Use a scale, not rigid numbers'],['可从 4、8、16、24、32px 选择一组常用间距，降低随意性。它不是禁止其他数字的规则。应根据内容密度、文字长度和屏幕空间调整，并在同类组件中保持一致。','A scale such as 4, 8, 16, 24 and 32px reduces arbitrary choices. It does not prohibit other values. Adapt spacing to content density, text length and available space, while keeping similar components consistent.']],
      [['区分声明宽度和占用宽度','Separate declared width from occupied width'],['content-box 的 width 指内容宽度，边框盒宽度还要加左右 padding 和 border。border-box 的 width 已包含这些部分。margin 位于边框外，不包含在两种 width 中。本演示显示实际盒尺寸和包含外边距的水平占用宽度。','With content-box, width sets the content width; add horizontal padding and borders to obtain the border-box width. With border-box, width already includes them. Margin is outside the border and belongs to neither declared width. This demo reports actual box dimensions and horizontal footprint including margins.']],
      [['让间距服务阅读','Make spacing serve reading'],['过小的内边距使文字贴近边缘，过大则压缩内容空间，可能造成频繁换行。不能用一个固定数值断言所有页面都“合理”。请结合当前卡片的标题、数值和说明判断，并比较英文模式。','Too little padding crowds text against the edge; too much reduces content space and may cause excessive wrapping. No single number is correct for every page. Judge the title, value and note together, and compare the English version.']]],
    takeaway:['先判断空白表达的是组件内部空间还是组件之间的关系，再选 padding、gap 或 margin。','Decide whether space belongs inside a component or between components, then choose padding, gap or margin.']},
    {title:['局部排列与对齐','Local Alignment with Flexbox'],short:['局部对齐','Alignment'],
    intro:['为同一个看板安排顶部筛选栏：搜索框能够伸缩，课程筛选保持可读，空间不足时允许换行。','Arrange the same dashboard’s filter bar: let the search field flex, keep the course selector readable, and allow wrapping when space is limited.'],
    task:['切换较长的文字，将预览宽度调到 390px，比较开启与关闭换行的结果。随后检查主轴与交叉轴变化。','Use longer labels and reduce preview width to 390px. Compare wrapping on and off, then inspect changes to the main and cross axes.'],
    theory:[
      [['对齐提供稳定的参照','Alignment creates a stable reference'],['工具栏里的搜索和筛选属于同一个任务组。统一边界与垂直对齐可以减少视觉跳跃。字号或控件高度不同时，需要有意识地选择居中、起点或基线对齐，而不是逐个移动元素。','Search and filtering belong to one task group. Shared edges and vertical alignment reduce visual jumps. When text sizes or control heights differ, deliberately choose center, start or baseline alignment instead of moving each element individually.']],
      [['先判断一维关系','Identify the one-dimensional relationship'],['工具栏主要处理一行内容的排列，适合 Flex。direction 决定主轴，justify-content 沿主轴分配空间，align-items 沿交叉轴对齐。改为 column 后，主轴变成纵向，这些属性的方向也随之改变。','A toolbar mainly arranges items along one line, so Flex is suitable. Direction sets the main axis; justify-content distributes space along it, while align-items aligns the cross axis. With column, the main axis becomes vertical and the property directions change accordingly.']],
      [['定义谁可以伸缩','Decide what may flex'],['搜索区域使用 flex:1 1 220px，允许参与剩余空间分配；课程选择区域保留自身内容尺寸。比起给所有控件固定宽度，这种规则更能表达任务优先级，但仍要检查最小可读宽度。','The search region uses flex:1 1 220px to share available space; the course region retains its content size. These rules express priorities better than fixed widths on every control, but minimum readable sizes still need checking.']],
      [['换行是一种布局决策','Wrapping is a layout decision'],['空间不足时换行通常比挤压文字更可读。gap 保持成员之间的统一距离，不增加容器外边缘的额外间距。若需要每一行的列严格对应，则应使用 Grid，而不是反复调整 Flex 子项。','When space is limited, wrapping is often clearer than squeezing text. Gap keeps consistent spacing between items without adding outer-edge space. If columns must align across rows, use Grid rather than repeatedly adjusting Flex items.']]],
    takeaway:['用 Flex 描述局部成员的关系：谁伸缩、如何对齐、何时换行。','Use Flex to describe local relationships: what flexes, how items align, and when they wrap.']},
    {title:['整体网格与主次关系','Grid & Content Priority'],short:['整体网格','Grid'],
    intro:['把指标、学习趋势和课程分布放进同一个网格。通过比例和跨列规则，让主要信息获得足够的阅读空间。','Place metrics, the learning trend and course distribution in one grid. Use proportions and spans to give primary information enough reading space.'],
    task:['比较等分、主次两列和跨列布局。观察主图的可读宽度，打开列线，核对下方代码与实际轨道。','Compare equal columns, primary/secondary columns and a spanning layout. Observe the main chart’s readable width, enable column guides and compare the tracks with the code below.'],
    theory:[
      [['网格用于协调多个区域','A grid coordinates regions'],['网格建立共享的列边界，让摘要、图表和说明具有秩序。它不仅是把内容平均切成几份。先确定模块的作用与最低空间需求，再决定列数和跨度。','A grid creates shared column edges, bringing order to summaries, charts and notes. It is more than dividing content into equal parts. Decide each module’s role and minimum space requirements before choosing columns and spans.']],
      [['比例应反映信息价值','Proportion should reflect information value'],['学习趋势需要展示时间变化，通常比课程分布需要更宽的区域。本案例用 2:1 比例作为起点；若任务变成比较课程，等分也可能合理。布局优劣取决于任务，不存在通用最佳比例。','A learning trend shows change over time and often needs more width than course distribution. This case starts with a 2:1 ratio; equal columns may be appropriate when comparing courses is the main task. Quality depends on the task, not a universal best ratio.']],
      [['理解剩余空间与最小尺寸','Understand free space and minimum sizes'],['fr 分配轨道中的可用空间。minmax(0,1fr) 允许轨道收缩，子项仍需 min-width:0 等规则避免内容撑破。允许缩小不代表文字会自动变得易读，所以还需要在窄屏重排。','The fr unit distributes available track space. minmax(0,1fr) allows tracks to shrink; children still need rules such as min-width:0 to avoid content expansion. Allowing shrinkage does not ensure readable text, so narrow layouts still need reflow.']],
      [['跨列建立共同边界','Spanning establishes shared edges'],['摘要横跨两列，可以与下方两张图表的整体外边界对齐。本演示的列线来自同一列模板，并包含当前 gap；它表示实际轨道，而非装饰性的背景方格。','A summary spanning two columns aligns with the combined outer edges of the charts below. The demo guides use the same column template and current gap. They show actual tracks rather than decorative background squares.']]],
    takeaway:['让内容决定网格，让网格维持秩序；用同一组轨道协调模块边界。','Let content determine the grid, then use shared tracks to keep module boundaries consistent.']},
    {title:['响应式与内容保留','Responsive Layout & Content'],short:['响应式','Responsive'],
    intro:['缩窄同一个看板，观察它从单列到多列的变化。演示使用独立页面视口和真实媒体查询，宽度数值就是内部视口宽度。','Resize the same dashboard and observe its transition between one and multiple columns. The demo uses an independent page viewport and real media queries; the number is the inner viewport width.'],
    task:['依次查看 519、520、759、760px，说明哪个规则开始生效。确认课程分布没有消失，并尝试窄屏中的导航菜单。','Inspect 519, 520, 759 and 760px and explain which rule becomes active. Verify that course distribution remains available, then try the narrow-screen navigation menu.'],
    theory:[
      [['断点由内容决定','Let content determine breakpoints'],['本案例以 520px 和 760px 作为经过布局安排的演示断点。它们不是所有设备的固定分类。实际项目应逐渐缩窄页面，在模块开始拥挤或失去可读性时决定重排位置。','This case uses 520px and 760px as demonstration breakpoints chosen for its layout. They are not universal device categories. In a real project, narrow the page gradually and choose reflow points where modules become crowded or difficult to read.']],
      [['先保障窄屏任务','Support narrow-screen tasks first'],['默认样式为单列，520px 起摘要变为多列，760px 起出现侧栏和两列图表。这就是从简单布局逐步增强。更宽的屏幕用于增加同时呈现的信息，而不是让字号无限变大。','The default layout is one column. At 520px, metrics become multiple columns; at 760px, a sidebar and two chart columns appear. This progressively enhances a simple baseline. Wider screens show more information together rather than enlarging text indefinitely.']],
      [['重排，不丢失内容','Reflow without losing content'],['窄屏把课程分布移动到主图下方，导航改为可展开菜单。重要内容不能因为屏幕变窄就无法访问。重排时保持合理文档顺序，并检查控件是否仍可操作。','On narrow screens, course distribution moves below the main chart and navigation becomes an expandable menu. Important content must remain accessible. Preserve a sensible document order and verify that controls still work.']],
      [['区分预览和外层网站','Separate preview and host page'],['拖动滑块改变的是预览内部视口，不是浏览器整个窗口。外层屏幕放不下预览时可以横向滚动查看，系统不会偷偷缩小画布或改变标注数值。外层教学页面本身也需要独立的小屏适配。','The slider changes the preview’s inner viewport, not the whole browser window. If the preview exceeds the host screen, scroll horizontally; the system does not silently shrink it or alter its label. The teaching page itself also needs its own responsive layout.']]],
    takeaway:['响应式的目标是保留任务和信息，让内容在不同空间中重新组织。','Responsive design preserves tasks and information by reorganizing content for different spaces.']},
    {title:['综合改进与自检','Composition & Review'],short:['综合案例','Review'],
    intro:['将前五节应用到同一个学习数据看板，比较初始反例与改进版。最终成果不仅要好看，还应能解释每一项布局选择。','Apply the previous five lessons to the same learning dashboard and compare the initial counterexample with the improved version. The result should look clear and explain the reasoning behind each layout choice.'],
    task:['在桌面和手机宽度分别比较前后版本。用层级、间距、对齐、内容保留四项标准检查改进版，再切换语言验证长文本。','Compare both versions at desktop and phone widths. Review hierarchy, spacing, alignment and content retention, then switch language to check longer text.'],
    theory:[
      [['用任务验证层级','Validate hierarchy against the task'],['能否先找到本周时长、完成课程和目标进度？能否进一步定位趋势与课程分布？用具体查找任务验证阅读路径，比只问页面是否漂亮更有依据。','Can users first find weekly study time, completed courses and goal progress? Can they then locate trends and course distribution? Concrete finding tasks validate the reading path more reliably than asking only whether the page looks attractive.']],
      [['组合工具，不堆叠补丁','Compose tools rather than patches'],['Grid 安排整体区域，Flex 排列局部工具栏，卡片内部使用正常文档流。用统一间距与最小宽度约束连接它们。局部组件应可以改变内容，而不依赖其他模块的偶然尺寸。','Grid arranges major regions, Flex organizes the local toolbar, and normal flow structures cards. Connect them with shared spacing and minimum-width constraints. Local components should tolerate content changes without depending on accidental dimensions elsewhere.']],
      [['检查语言和尺寸变化','Check language and size changes'],['英文可能占据更长的横向空间。切换语言后，应保留当前章节和演示参数，再观察按钮、标题、卡片是否换行合理。窄屏不能通过隐藏主要内容来掩盖溢出问题。','English may require more horizontal space. Language switching should preserve the current lesson and demo parameters; then inspect wrapping in buttons, headings and cards. Hiding primary content is not a valid way to conceal overflow.']],
      [['区分布局原型与数据产品','Distinguish a layout prototype from a data product'],['图表与数值是用于教学的模拟内容，重点是模块布局，不能据此得出真实学习表现结论。筛选栏在这里演示排列关系；完整数据查询和导出功能不属于本章目标，因此不放置无效的导出按钮。','Charts and values are simulated teaching content focused on module layout; they do not support conclusions about real learning performance. The filter bar demonstrates arrangement. Full data querying and export are outside this chapter, so there is no inactive export button.']]],
    takeaway:['用可解释的原则、可运行的代码和可观察的交互共同证明布局改进。','Demonstrate improvements through explainable principles, working code and observable interaction.']}
  ]
};
