// The sample course explains the purpose and pitfalls of each implementation.
window.TeachingNotes = [
 {why:['侧栏固定宽度，内容列用 minmax(0,1fr) 接收剩余空间；摘要先于图表出现在文档中，让视觉顺序和阅读任务保持一致。','The sidebar has a fixed width while minmax(0,1fr) gives remaining space to the content. Metrics precede charts in the document so visual order supports the reading task.'],pitfall:['不要只用 CSS order 把重要内容挪到前面：键盘与辅助阅读顺序可能仍跟随文档。改进前视图用于观察问题，正式页面应直接采用合理的内容顺序。','Do not rely only on CSS order to promote important content: keyboard and assistive reading order may still follow the document. The Before view illustrates a problem; the final document should use a sensible content order.']},
 {why:['border-box 将内边距与边框纳入声明宽度，适合控制卡片边界；content-box 则便于观察内容宽度之外的累加。两种模式下都单独计算外边距。','Border-box includes padding and borders in the declared width, helping control card boundaries. Content-box makes the additional space outside content visible. Margins are accounted for separately in both modes.'],pitfall:['不要把包含外边距的水平占用称为元素 width；也不要把内边距无限增大。相同声明宽度下，border-box 的内容区域会变窄，需要检查文本换行。','Do not call the horizontal footprint including margins the element width, or increase padding without limits. At a fixed declared width, border-box reduces content space, so text wrapping needs checking.']},
 {why:['搜索区允许增长和收缩，筛选区保留内容尺寸；wrap 与 gap 共同维持小屏下的组内关系。列方向会同时改变主轴，因此对齐要结合 direction 理解。','The search area may grow and shrink while the filter retains its content size. Wrap and gap preserve relationships on narrow screens. Column direction changes the main axis, so alignment must be interpreted with direction.'],pitfall:['若给每个成员固定宽度并关闭换行，长文本容易溢出。实验中可故意关闭 wrap 观察问题；最终方案应检查中英文长文本，而不是只看短标签。','Fixed widths combined with no wrapping can overflow with long text. Disable wrap to observe the problem, then check long labels in both languages when choosing a final layout.']},
 {why:['共享列模板使不同模块具有共同边界；主次 2:1 为趋势留出更多空间，跨列让摘要与整体网格对齐。辅助线使用相同轨道与 gap。','Shared tracks align module boundaries. The 2:1 option gives the trend more space, while spanning aligns the summary with the whole grid. Guides use the same tracks and gap.'],pitfall:['不要给两张卡片各设 50% 后再加 gap，也不要把 fr 理解成固定像素。允许轨道收缩仍需检查内容是否可读，窄屏可能需要改单列。','Do not assign 50% to each of two cards and then add a gap, or interpret fr as fixed pixels. Shrinkable tracks still need readability checks; narrow layouts may need one column.']},
 {why:['单列是默认状态，520px 和 760px 逐步增加列数与导航区域。演示使用真实独立视口，同一套媒体查询用于代码展示和实际渲染。','One column is the baseline; 520px and 760px progressively add columns and navigation space. The demo uses a real independent viewport and shares media queries between the code and rendering.'],pitfall:['不要把 520/760px 当成所有设备的标准，也不要仅靠隐藏图表解决空间不足。检查 519/520/759/760px 边界附近，以及导航展开后的内容可达性。','Do not treat 520/760px as universal device standards or hide charts merely to save space. Check around 519/520/759/760px and verify access to content after expanding navigation.']},
 {why:['Grid 负责整体，Flex 负责工具栏，卡片内采用正常文档流。共享规则让同一案例在不同尺寸和语言下保持一致的内容关系。','Grid organizes the whole page, Flex handles the toolbar, and cards use normal flow. Shared rules maintain content relationships across screen sizes and languages.'],pitfall:['不要把装饰方格当作真实列线，也不要用删掉次要图表制造“适配成功”。先比较查找任务、内容保留与可读性，再调整颜色、阴影等细节。','Do not confuse decorative squares with real column guides or remove secondary charts to claim successful adaptation. Compare finding tasks, content retention and readability before refining colors or shadows.']}
];
